version: '3.8'
services: 
  web:
    environment:
      - APP_SECRET_KEY=c2e3defa-c8d9-47b1-9c05-a6f8bf620e45
      - FLASK_ENV=development
      - DB_ECHO=False
      - DB_TRACK_MODIFICATIONS=False
      - DATABASE_URL=sqlite:///polynomial_evaluator.db
      - TEST_DATABASE_URL=sqlite:///polynomial_evaluator_test.db
    build:
      context: .
    ports:
    - 8000:5000
    volumes:
    - ./:/app